server:
  port: 8091

spring:
    main:
        allow-bean-definition-overriding: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect             
    flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration

    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:convenios
        username: sa
        password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

