info:
  component: Edge Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    convenio-service:
      path: /convenio-service/**
      serviceId: convenio-service


ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    registerWithEureka: false

server:
  port: 8060